#超参数设置

lr: 0.00001 #稳定阶段学习率
momentum: 0.999
weight_decay: 0.0005


warmup_epochs: 5.0  # warmup epochs
warmup_momentum: 0.8  # warmup initial momentum
warmup_bias_lr: 0.1  # warmup initial bias lr


#损失权重
box: 0.05
cls: 0.5
obj: 1.0


